name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.5
  drift_dev: ^2.34.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/recipes/
  fonts:
    - family: Bricolage Grotesque
      fonts:
        - asset: assets/fonts/Bricolage_Grotesque/BricolageGrotesque-Regular.ttf
          weight: 400
        - asset: assets/fonts/Bricolage_Grotesque/BricolageGrotesque-Medium.ttf
          weight: 500
        - asset: assets/fonts/Bricolage_Grotesque/BricolageGrotesque-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Bricolage_Grotesque/BricolageGrotesque-Bold.ttf
          weight: 700
        - asset: assets/fonts/Bricolage_Grotesque/BricolageGrotesque-ExtraBold.ttf
          weight: 800
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrains_Mono/JetBrainsMono-Bold.ttf
          weight: 700
